package repo

import (
	"context"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// runGit invokes git with the given args and returns its combined output.
// The working directory and any extra env are taken from the caller-built
// exec.Cmd so each call site can be explicit about scope.
func runGit(ctx context.Context, cwd string, env []string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = cwd
	if len(env) > 0 {
		cmd.Env = env
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("git %s: %w\n%s", args[0], err, trimOutput(out))
	}
	return string(out), nil
}

// clone runs `git clone <authedURL> <destPath>`.
func clone(ctx context.Context, authedURL, destPath string) error {
	_, err := runGit(ctx, "", nil, "clone", "--", authedURL, destPath)
	return err
}

// setRemoteURL rewrites the origin URL in an existing clone. Used right
// after clone to strip the embedded PAT from .git/config.
func setRemoteURL(ctx context.Context, repoPath, cleanURL string) error {
	_, err := runGit(ctx, repoPath, nil, "remote", "set-url", "origin", cleanURL)
	return err
}

// currentBranch returns the short name of the currently checked-out branch,
// or the literal "HEAD" when the repo is in detached-HEAD state.
func currentBranch(ctx context.Context, repoPath string) (string, error) {
	out, err := runGit(ctx, repoPath, nil, "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}

// defaultBranch resolves origin/HEAD to its short branch name (e.g. "main").
// Returns an empty string (no error) when origin/HEAD is not set.
func defaultBranch(ctx context.Context, repoPath string) (string, error) {
	out, err := runGit(ctx, repoPath, nil, "symbolic-ref", "--short", "refs/remotes/origin/HEAD")
	if err != nil {
		// Not fatal — some repos don't have this ref configured.
		return "", nil
	}
	ref := strings.TrimSpace(out)
	// "origin/main" → "main"
	if i := strings.IndexByte(ref, '/'); i >= 0 {
		ref = ref[i+1:]
	}
	return ref, nil
}

// setGlobalUserConfig writes user.name and user.email to the current
// HOME/.gitconfig. Idempotent — called once on bot startup so that git
// commits made by the Claude-spawned subprocess carry the operator's
// identity.
func SetGlobalUserConfig(ctx context.Context, name, email string) error {
	if _, err := runGit(ctx, "", nil, "config", "--global", "user.name", name); err != nil {
		return err
	}
	if _, err := runGit(ctx, "", nil, "config", "--global", "user.email", email); err != nil {
		return err
	}
	return nil
}

// InstallCredentialHelper writes a tiny credential-helper script that prints
// the GitHub PAT from $GITHUB_PAT in the calling process's env, then wires
// git's global config to use it. After this runs, any `git pull/push/fetch`
// against an HTTPS GitHub URL (including ones invoked by Claude inside its
// subprocess) authenticates without the URL needing the PAT inlined.
//
// Idempotent: rewrites the script on each call.
func InstallCredentialHelper(ctx context.Context, home string) error {
	if home == "" {
		return fmt.Errorf("credential helper: empty HOME")
	}
	scriptPath := filepath.Join(home, ".git-credential-pat.sh")
	body := "#!/bin/sh\n" +
		"# Auto-generated by orb. Reads $GITHUB_PAT from the\n" +
		"# environment so git invocations under this HOME pick it up.\n" +
		"echo username=x-access-token\n" +
		"echo password=\"$GITHUB_PAT\"\n"
	if err := os.WriteFile(scriptPath, []byte(body), 0o700); err != nil {
		return fmt.Errorf("credential helper: write script: %w", err)
	}
	if _, err := runGit(ctx, "", nil, "config", "--global", "credential.helper", "!"+scriptPath); err != nil {
		return fmt.Errorf("credential helper: git config: %w", err)
	}
	return nil
}

// --- read-only helpers ----------------------------------------------------

// Status returns `git status --short` output for repoPath.
func Status(ctx context.Context, repoPath string) (string, error) {
	return runGit(ctx, repoPath, nil, "status", "--short", "--branch")
}

// Diff returns `git diff` (optionally --staged) for repoPath. The no-color
// form keeps the output Telegram-friendly.
func Diff(ctx context.Context, repoPath string, staged bool) (string, error) {
	args := []string{"diff", "--no-color"}
	if staged {
		args = append(args, "--staged")
	}
	return runGit(ctx, repoPath, nil, args...)
}

// StatusShort is Status without the branch header; used inside commit preview.
func StatusShort(ctx context.Context, repoPath string) (string, error) {
	return runGit(ctx, repoPath, nil, "status", "--short")
}

// --- mutating helpers -----------------------------------------------------

// branchNamePattern is the client-side sanity check. Git itself has more
// rules (see git-check-ref-format) but this catches the obvious junk.
var branchNamePattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._\-/]{0,99}$`)

// ValidateBranchName returns nil when name looks safe to pass to git
// checkout -b.
func ValidateBranchName(name string) error {
	if !branchNamePattern.MatchString(name) {
		return fmt.Errorf("invalid branch name %q", name)
	}
	if strings.Contains(name, "..") || strings.HasSuffix(name, ".lock") {
		return fmt.Errorf("invalid branch name %q", name)
	}
	return nil
}

// CreateBranch runs `git checkout -b <name>` in repoPath.
func CreateBranch(ctx context.Context, repoPath, name string) (string, error) {
	if err := ValidateBranchName(name); err != nil {
		return "", err
	}
	return runGit(ctx, repoPath, nil, "checkout", "-b", name)
}

// Checkout switches to an existing local branch. Refuses if the tree is
// dirty in a way git can't reconcile.
func Checkout(ctx context.Context, repoPath, name string) (string, error) {
	if err := ValidateBranchName(name); err != nil {
		return "", err
	}
	return runGit(ctx, repoPath, nil, "checkout", name)
}

// LocalBranches lists short names of every local branch in repoPath, sorted
// alphabetically. Empty slice (no error) when there are none.
func LocalBranches(ctx context.Context, repoPath string) ([]string, error) {
	out, err := runGit(ctx, repoPath, nil, "for-each-ref", "--format=%(refname:short)", "refs/heads/")
	if err != nil {
		return nil, err
	}
	var branches []string
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			branches = append(branches, line)
		}
	}
	return branches, nil
}

// CommitAll stages every change (`git add -A`) and records a commit with msg.
func CommitAll(ctx context.Context, repoPath, msg string) (string, error) {
	if strings.TrimSpace(msg) == "" {
		return "", fmt.Errorf("empty commit message")
	}
	if _, err := runGit(ctx, repoPath, nil, "add", "-A"); err != nil {
		return "", err
	}
	return runGit(ctx, repoPath, nil, "commit", "-m", msg)
}

// Push pushes branch to origin. The authed URL is passed explicitly so the
// PAT is never written to .git/config. Force pushes are intentionally not
// supported.
func Push(ctx context.Context, repoPath, cleanURL, pat, branch string) (string, error) {
	auth, err := authedURL(cleanURL, pat)
	if err != nil {
		return "", err
	}
	out, err := runGit(ctx, repoPath, nil, "push", auth, branch)
	if err != nil {
		return out, scrubPAT(err, pat)
	}
	return out, nil
}

// Pull runs `git pull --ff-only <authed-url> <branch>`. On non-fast-forward
// git exits non-zero and the caller gets the error plus output.
func Pull(ctx context.Context, repoPath, cleanURL, pat, branch string) (string, error) {
	auth, err := authedURL(cleanURL, pat)
	if err != nil {
		return "", err
	}
	out, err := runGit(ctx, repoPath, nil, "pull", "--ff-only", auth, branch)
	if err != nil {
		return out, scrubPAT(err, pat)
	}
	return out, nil
}

// CurrentBranch exports currentBranch for callers outside this package.
func CurrentBranch(ctx context.Context, repoPath string) (string, error) {
	return currentBranch(ctx, repoPath)
}

// --- URL handling ---------------------------------------------------------

// normalizeURL accepts a user-supplied URL and returns a clean canonical
// form suitable for storage. SSH and ssh-style URLs are rejected since our
// auth strategy is HTTPS + PAT.
func normalizeURL(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", fmt.Errorf("empty url")
	}
	if strings.HasPrefix(raw, "git@") || strings.HasPrefix(raw, "ssh://") {
		return "", fmt.Errorf("only HTTPS URLs are supported (got ssh-style)")
	}
	if !strings.Contains(raw, "://") {
		// Accept bare "github.com/foo/bar" too.
		raw = "https://" + raw
	}
	u, err := url.Parse(raw)
	if err != nil {
		return "", fmt.Errorf("parse url: %w", err)
	}
	if u.Scheme != "https" {
		return "", fmt.Errorf("only https URLs are supported (got %q)", u.Scheme)
	}
	if u.Host == "" || u.Path == "" || u.Path == "/" {
		return "", fmt.Errorf("url missing host or path")
	}
	// Drop any embedded userinfo — we inject our own PAT at runtime.
	u.User = nil
	// Drop query/fragment; not meaningful for git clone.
	u.RawQuery = ""
	u.Fragment = ""
	if !strings.HasSuffix(u.Path, ".git") {
		u.Path += ".git"
	}
	return u.String(), nil
}

// authedURL embeds the GitHub PAT into a clean HTTPS URL for a one-off git
// operation. The returned URL must never be persisted.
func authedURL(cleanURL, pat string) (string, error) {
	u, err := url.Parse(cleanURL)
	if err != nil {
		return "", fmt.Errorf("parse clean url: %w", err)
	}
	u.User = url.UserPassword("x-access-token", pat)
	return u.String(), nil
}

// aliasFromURL derives a human-friendly alias from a repo URL. For
// https://github.com/foo/bar.git it returns "bar".
func aliasFromURL(cleanURL string) string {
	u, err := url.Parse(cleanURL)
	if err != nil {
		return ""
	}
	p := strings.TrimSuffix(u.Path, ".git")
	p = strings.TrimPrefix(p, "/")
	if i := strings.LastIndexByte(p, '/'); i >= 0 {
		p = p[i+1:]
	}
	return p
}

// trimOutput shortens git output for inclusion in Go error messages.
func trimOutput(b []byte) string {
	const max = 600
	if len(b) > max {
		return string(b[:max]) + "…"
	}
	return string(b)
}
